### ISSUE TITLE
Thread groups count in getBuffers()

### ISSUE THREAD

**Issue by golunovas** [christopherhelf/iOS-Metal-HaarCascade#1]
Good job! Thank you! 

Looks like parameters of dispatchThreadgroups should be in this order:
`encoder.dispatchThreadgroups(MTLSizeMake((numberOfClassifiers+31)/32, 1, 1), threadsPerThreadgroup: MTLSizeMake(32, 1, 1))`

**Comment by christopherhelf** [comment]
Hi, thanks for the input!

I've actually just now pushed a completely rewritten version of this repo, which performs much better, processes stages in parallel and does grouping on the GPU as well - I've put the old version in another branch.

**Comment by golunovas** [comment]
Thanks for the update. Great results!
