### ISSUE TITLE
validateNewTexture:58: failed assertion `BytesPerRow of a buffer-backed texture with pixelFormat(MTLPixelFormatRGBA32Float) must be aligned to 64 bytes, found bytesPerRow(46608)'

### ISSUE THREAD

**Issue by Dabin22** [christopherhelf/iOS-Metal-HaarCascade#3]
I was interested in this project and forked. And I tried to run it but it did not work.

The thread stops with the same content as the title. The code of the stopping part is as follows. How do I fix it? The device used is iphone 8 (ios11.0) xcode 9

'let classifiersTexture = classifiersBuffer.makeTexture(descriptor: classifiersDescriptor, offset: 0, bytesPerRow: classifierArray.count * MemoryLayout<Float32>.size)'

thanks

**Comment by christopherhelf** [comment]
I haven't worked on this in quite a while, but it seems nowadays texture rows must be 64-byte aligned (i think on mac osx its even 128). try zero padding the classifierArray before allocating the buffer with something like

    let toPad = (16-classifierArray.count%16)
    if toPad > 0 {
        classifierArray = classifierArray + [Float32](count: toPad, repeatingValue: 0.0)
    }
